/*-------------------------------------------------------------------------
 *
 * pl_unreserved_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef PL_UNRESERVED_KWLIST_D_H
#define PL_UNRESERVED_KWLIST_D_H

#include "common/kwlookup.h"

static const char UnreservedPLKeywords_kw_string[] =
	"absolute\0"
	"alias\0"
	"and\0"
	"array\0"
	"assert\0"
	"backward\0"
	"call\0"
	"chain\0"
	"close\0"
	"collate\0"
	"column\0"
	"column_name\0"
	"commit\0"
	"constant\0"
	"constraint\0"
	"constraint_name\0"
	"continue\0"
	"current\0"
	"cursor\0"
	"datatype\0"
	"debug\0"
	"default\0"
	"detail\0"
	"diagnostics\0"
	"do\0"
	"dump\0"
	"elseif\0"
	"elsif\0"
	"errcode\0"
	"error\0"
	"exception\0"
	"execute\0"
	"exit\0"
	"fetch\0"
	"first\0"
	"forward\0"
	"get\0"
	"hint\0"
	"import\0"
	"info\0"
	"insert\0"
	"is\0"
	"last\0"
	"log\0"
	"merge\0"
	"message\0"
	"message_text\0"
	"move\0"
	"next\0"
	"no\0"
	"notice\0"
	"open\0"
	"option\0"
	"perform\0"
	"pg_context\0"
	"pg_datatype_name\0"
	"pg_exception_context\0"
	"pg_exception_detail\0"
	"pg_exception_hint\0"
	"pg_routine_oid\0"
	"print_strict_params\0"
	"prior\0"
	"query\0"
	"raise\0"
	"relative\0"
	"return\0"
	"returned_sqlstate\0"
	"reverse\0"
	"rollback\0"
	"row_count\0"
	"rowtype\0"
	"schema\0"
	"schema_name\0"
	"scroll\0"
	"slice\0"
	"sqlstate\0"
	"stacked\0"
	"strict\0"
	"table\0"
	"table_name\0"
	"type\0"
	"use_column\0"
	"use_variable\0"
	"variable_conflict\0"
	"warning";

static const uint16 UnreservedPLKeywords_kw_offsets[] = {
	0,
	9,
	15,
	19,
	25,
	32,
	41,
	46,
	52,
	58,
	66,
	73,
	85,
	92,
	101,
	112,
	128,
	137,
	145,
	152,
	161,
	167,
	175,
	182,
	194,
	197,
	202,
	209,
	215,
	223,
	229,
	239,
	247,
	252,
	258,
	264,
	272,
	276,
	281,
	288,
	293,
	300,
	303,
	308,
	312,
	318,
	326,
	339,
	344,
	349,
	352,
	359,
	364,
	371,
	379,
	390,
	407,
	428,
	448,
	466,
	481,
	501,
	507,
	513,
	519,
	528,
	535,
	553,
	561,
	570,
	580,
	588,
	595,
	607,
	614,
	620,
	629,
	637,
	644,
	650,
	661,
	666,
	677,
	690,
	708,
};

#define UNRESERVEDPLKEYWORDS_NUM_KEYWORDS 85

static int
UnreservedPLKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[171] = {
		83,    27,    32767, 32767, 28,    32767, 32767, 0,
		12,    59,    -22,   51,    39,    32767, 32767, 0,
		20,    14,    7,     23,    76,    32767, 32767, 32767,
		43,    32767, 32767, 32767, 28,    32767, 79,    -19,
		19,    -33,   32767, 25,    24,    32767, 0,     32767,
		0,     32767, 17,    32767, 34,    0,     32767, 27,
		54,    6,     32767, -61,   0,     27,    32767, -18,
		12,    55,    0,     32767, 0,     32767, 0,     49,
		-12,   0,     32767, 32767, 73,    32767, 26,    32767,
		0,     12,    32767, 26,    32767, 32767, 46,    32767,
		25,    -59,   13,    14,    -10,   32767, -56,   32767,
		68,    32767, 32767, 54,    33,    0,     -17,   -68,
		0,     0,     -34,   0,     43,    59,    32767, 61,
		0,     0,     78,    1,     44,    32767, 32767, 32767,
		63,    32767, 1,     0,     3,     32767, 69,    32767,
		-9,    28,    32767, 69,    38,    32767, 25,    32767,
		32767, 0,     0,     79,    32767, 0,     32767, 32767,
		0,     84,    32767, 32767, 2,     70,    83,    48,
		14,    32767, 9,     32,    -30,   32767, 32767, 72,
		32767, 32767, 82,    0,     0,     40,    9,     -3,
		32767, 24,    0,     0,     0,     -7,    -10,   32767,
		0,     0,     32767
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 0;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 31 + c;
	}
	return h[a % 171] + h[b % 171];
}

static const ScanKeywordList UnreservedPLKeywords = {
	UnreservedPLKeywords_kw_string,
	UnreservedPLKeywords_kw_offsets,
	UnreservedPLKeywords_hash_func,
	UNRESERVEDPLKEYWORDS_NUM_KEYWORDS,
	20
};

#endif							/* PL_UNRESERVED_KWLIST_D_H */
